CREATE DATABASE fitbody;

CREATE TABLE accounts(
  account_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(254) NOT NULL,
  email VARCHAR(254) NOT NULL,
  password VARCHAR(254) NOT NULL
);

CREATE TABLE workout(
  workout_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  w_name VARCHAR(255) NOT NULL,
  created  DATE NOT NULL DEFAULT CURRENT_DATE,
  account_id INT,
  CONSTRAINT fk_account
  FOREIGN KEY(account_id)
  REFERENCES accounts(account_id)
);

CREATE TABLE exercise(
  ex_id INT,
  ex_name VARCHAR(255) NOT NULL,
  workout_id INT,
  CONSTRAINT fk_workout
  FOREIGN KEY(workout_id)
  REFERENCES workout(workout_id),
  PRIMARY KEY(ex_id,workout_id)
);

CREATE TABLE sets(
  set_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  s_order INT,
  reps INT,
  weight INT,
  w_unit VARCHAR(100),
  r_unit VARCHAR(100),
  ex_id INT,
  workout_id INT,
  CONSTRAINT fk_exercise
  FOREIGN KEY(ex_id,workout_id)
  REFERENCES exercise(ex_id,workout_id)
);

CREATE TABLE session(
  session_id INT,
  session_date DATE NOT NULL,
  account_id INT,
  workout_id INT,
  CONSTRAINT fk1 FOREIGN KEY (account_id)
  REFERENCES accounts (account_id),
  CONSTRAINT fk2 FOREIGN KEY (workout_id)
  REFERENCES workout (workout_id)
);