CREATE DATABASE fitbody;

CREATE TABLE accounts(
  account_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(254) NOT NULL,
  email VARCHAR(254) NOT NULL,
  password VARCHAR(254) NOT NULL
);

CREATE TABLE workout(
  workout_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  w_name VARCHAR(255) NOT NULL,
  created  DATE NOT NULL DEFAULT CURRENT_DATE,
  account_id INT,
  CONSTRAINT fk_account
  FOREIGN KEY(account_id)
  REFERENCES accounts(account_id)
);

CREATE TABLE exercise(
  ex_id INT,
  ex_name VARCHAR(255) NOT NULL,
  CONSTRAINT fk_workout
    FOREIGN KEY(workout_id)
      REFERENCES workout(workout_id) NOT NULL,
  PRIMARY KEY(ex_id,fk_workout)
);